export const SpecialEffects = {
    'БУДЬ ДРУГОМ.jpg': 'Choose_AnotherPlayer_Dont_Vote_Against_You_AllGame',
    'ВЗЯЛ С СОБОЙ.jpg': 'Choose_BunkerCard_Move_Any_Open_BunkerCard_From_Bunker_To_EliminatedBunker_If_I_Eliminated',
    'ВКЛЮЧИЛ СВЕТ.jpg': 'Choose_BunkerCard_Change_Any_BunkerCard_Open_With_BunkerDeck',
    'ГРОМКИЙ ГОЛОС.jpg': 'My_Vote_Has_2_Vote',    
    'ДАВАЙТЕ НА ЧИСТОТУ БАГАЖА.jpg': 'Mix_All_Open_BaggageCard_For_NoEliminated',
    'ДАВАЙТЕ НА ЧИСТОТУ БИОЛОГИЯ.jpg': 'Mix_All_Open_BiologyCard_For_NoEliminated'                                                                                                                                                                                                                           ,
    'ДАВАЙТЕ НА ЧИСТОТУ ЗДОРОВЬЯ.jpg': 'Mix_All_Open_HealthCard_For_NoEliminated',
    'ДАВАЙТЕ НА ЧИСТОТУ ФАКТОВ.jpg': 'Mix_All_Open_FactsCard_For_NoEliminated',
    'ДАВАЙТЕ НА ЧИСТОТУ ХОББИ.jpg': 'Mix_All_Open_HobbyCard_For_NoEliminated',
    'ДИВЕРСИЯ.jpg': 'Choose_BunkerCard_Delete_Open_BunkerCard_From_Bunker_If_I_Eliminated',
    'ДИСКРЕДИТАЦИЯ.jpg': 'Choose_Any_Player_Dont_Vote_Round',
    'ЗАЩИТИ ИГРОКА СЛЕВА.jpg': 'If_Player_Eliminated_Next_Apply_Voice_Myself_While_I_NotEliminated',
    'ЗАЩИТИ ИГРОКА СПРАВА.jpg': 'If_Player_Eliminated_Prev_Apply_Voice_Myself_While_I_NotEliminated',
    'ЗАЩИТИ МЛАДШЕГО.jpg': 'If_Player_Eliminated_Low_Age_And_Open_HealthCard_Apply_Voice_Myself_While_I_NotEliminated',
    'ЗАЩИТИ СМЕЛОГО.jpg': 'If_Player_Eliminated_FirstOpen_Open_HealthCard_Apply_Voice_Myself_While_I_NotEliminated',
    'ЗАЩИТИ СТАРШЕГО.jpg': 'If_Player_Eliminated_High_Age_And_Open_HealthCard_Apply_Voice_Myself_While_I_NotEliminated',
    'КОМПРОМАТ.jpg': 'Choose_AnotherPlayer_AgainstVoteMultiply_2_And_I_Dont_Vote_Round',
    'МНЕ НУЖНЕЕ.jpg': 'Choose_BaggageCard_Take_BaggageCard_From_AnotherPlayer_And_Player_Get_SpecialCard',
    'МОЛЧАНИЕ.jpg': 'All_Players_NoTalk_Round',
    'ОБМЕН КАРТ БАГАЖ.jpg': 'Choose_BaggageCard_Change_Open_BaggageCard_With_Left_Or_Right_player',
    'ОБМЕН КАРТ БИОЛОГИЯ.jpg': 'Choose_BiologyCard_Change_Open_BiologyCard_With_Left_Or_Right_player',
    'ОБМЕН КАРТ ЗДОРОВЬЕ.jpg': 'Choose_HealthCard_Change_Open_HealthCard_With_Left_Or_Right_player',
    'ОБМЕН КАРТ ФАКТОВ.jpg': 'Choose_FactCard_Change_Open_FactCard_With_Left_Or_Right_player',
    'ОБМЕН КАРТ ХОББИ.jpg': 'Choose_HobbyCard_Change_Open_HobbyCard_With_Left_Or_Right_player',
    'ПЛАН Б.jpg': 'All_Players_ChangeVote_And_DontVoteSame',
    'ПРОСРОЧЕННЫЕ ТАБЛЕТКИ.jpg': 'Choose_Player_Change_Open_HealthCard_Any_Player_With_HealthDeck',
    'ПРЯМОЙ ВОПРОС.jpg': 'Choose_Type_ChooseType_I_MustChoose_Players_All',
    'ТАЙНАЯ УГРОЗА.jpg': 'If_I_Eliminated_To_Bunker_Has_Danger_Defend_Or_Deal',
    'ФЕЙКОВЫЙ ДИПЛОМ.jpg': 'Choose_ProffesionCard_Change_Open_ProffesionCard_Any_Player_With_ProffessionDeck',
    'ХОРОШИЕ ТАБЛЕТКИ.jpg': 'Choose_HealthCard_Delete_Open_HealthCard_Any_Player',
}

